config/routes.rb
MyShop::Application.routes.draw do
  root 'root#index'

  get '/signin' => redirect('/auth/colormeshop')
  get '/auth/colormeshop/callback', to: 'sessions#create'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionHelper

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    self.current_user = auth_hash
    redirect_to '/'
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def current_user
    session[:current_user]
  end

  def current_user=(auth_hash)
    session[:current_user] = auth_hash
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyShop</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/root/index.html.erb
<% if current_user %>
  Hello, <%= current_user.info.name %>
<% else %>
  <%= link_to 'Please sign in', signin_path %>
<% end %>